import { describe,it,before } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { randomUUID } from 'node:crypto'
import { all,db,id,now,one,run } from '../lib/server/db'
import { AppError,hash,passwordHash,passwordMatches,publicUser,redeemToken,tokenFor,type Actor } from '../lib/server/auth'
import { adjustStock,assignDriver,catalogue,changeStatus,commissionAmount,listOrders,orderDetails,paymentTotals,payout,placeOrder,receiveStock,recordPayment } from '../lib/server/orders'
import { commissionsFor,overview,publicCatalogue,saveDriver,saveHotel,saveProduct,savePromotion } from '../lib/server/platform'
import { confirmDelivery,deliveryDetails } from '../lib/server/delivery'
import { processNotifications } from '../lib/server/notifications'
import { csvReport,pdfReport,reportRows } from '../lib/server/reports'

process.env.DATABASE_PATH=path.join(mkdtempSync(path.join(tmpdir(),'nungwi-tests-')),'test.sqlite')
process.env.APP_URL='http://localhost:3000'
delete process.env.TWILIO_ACCOUNT_SID;delete process.env.TWILIO_AUTH_TOKEN;delete process.env.RESEND_API_KEY
let admin:Actor,customer:Actor,other:Actor,stock:Actor,manager:Actor,hotelId:string,driverId:string
const future=(days=60)=>new Date(Date.now()+days*86400000).toISOString()
function user(role:Actor['role'],hotel:string|null=null){const userId=id();run('INSERT INTO users (id,email,name,phone,password,role,hotel_id,created_at) VALUES (?,?,?,?,?,?,?,?)',userId,`${userId}@example.test`,`${role} test`,'+255700000000',passwordHash('Test-only-password-2026'),role,hotel,now());return publicUser(one('SELECT * FROM users WHERE id=?',userId)!)}
function product(extra:Record<string,any>={}){return saveProduct(admin,{name:'Test beverage',category:'Beer',price:2000,cost:800,sku:randomUUID(),...extra})}
function stockIn(product_id:string,quantity=100,expires_at=future(),cost=800){return receiveStock(admin,{product_id,quantity,label:randomUUID(),expires_at,cost,reason:'Test receipt'})}
function payload(productId:string,qty=1,extra:Record<string,any>={}){return {items:[{product_id:productId,quantity:qty}],recipient:'Test Guest',phone:'+255700000001',address:'Test hotel, room 4',payment_method:'cash',idempotency_key:randomUUID(),...extra}}
function deliver(orderId:string,code:string){changeStatus(admin,orderId,'Confirmed');changeStatus(admin,orderId,'Preparing');assignDriver(admin,orderId,{driver_id:driverId,eta:'20 minutes',instructions:'Reception'});changeStatus(admin,orderId,'Out for delivery');changeStatus(admin,orderId,'Delivered',code)}
before(()=>{db();admin=user('admin');customer=user('customer');other=user('customer');stock=user('stock');hotelId=saveHotel(admin,{name:'Test hotel',contact:'Hotel manager',phone:'+255700000002',address:'Nungwi',code:'TEST-HOTEL',rule:{method:'percentage',value:10,scope:'referral',tiers:[]}});manager=user('hotel_manager',hotelId);driverId=saveDriver(admin,{name:'Test driver',phone:'+255700000003',vehicle:'motorcycle',registration:'T-TEST'})})

describe('persistent ordering and stock invariants',()=>{
 it('does not invent opening sales or stock',()=>{assert.equal(one('SELECT COUNT(*) AS n FROM orders')!.n,0);assert.equal(catalogue().find(p=>p.id==='1')!.available,0)})
 it('reserves FEFO stock, deduplicates placement, and releases cancellation exactly once',()=>{
  const p=product();const later=stockIn(p,10,future(90));const earlier=stockIn(p,5,future(30));const input=payload(p,7);const order=placeOrder(customer,input)
  assert.equal(order.status,'Pending');assert.equal(one('SELECT reserved FROM batches WHERE id=?',earlier)!.reserved,5);assert.equal(one('SELECT reserved FROM batches WHERE id=?',later)!.reserved,2)
  const count=one('SELECT COUNT(*) AS n FROM notifications')!.n;assert.equal(placeOrder(customer,input).id,order.id);assert.equal(one('SELECT COUNT(*) AS n FROM notifications')!.n,count)
  changeStatus(admin,order.id,'Cancelled');changeStatus(admin,order.id,'Cancelled');assert.equal(catalogue().find(row=>row.id===p)!.available,15)
 })
 it('rolls back an entire multi-product order when any product is short',()=>{const a=product();const b=product();stockIn(a,10);stockIn(b,1);const before=one('SELECT COUNT(*) AS n FROM orders')!.n;assert.throws(()=>placeOrder(customer,payload(a,2,{items:[{product_id:a,quantity:2},{product_id:b,quantity:2}]})),/enough unexpired stock/);assert.equal(catalogue().find(p=>p.id===a)!.reserved,0);assert.equal(one('SELECT COUNT(*) AS n FROM orders')!.n,before)})
 it('prevents overselling across sequential concurrent attempts',()=>{const p=product();stockIn(p,1);placeOrder(customer,payload(p));assert.throws(()=>placeOrder(other,payload(p)),/enough unexpired stock/);assert.equal(catalogue().find(row=>row.id===p)!.available,0)})
 it('shares stock between bottles and crates without double allocating',()=>{const p=product({units:[{unit:'crate',unit_size:24,price:40000,hotel_price:38000,deposit:1000}]});stockIn(p,25);const order=placeOrder(customer,payload(p,1,{items:[{product_id:p,quantity:1,unit:'crate'},{product_id:p,quantity:1,unit:'bottle'}]}));assert.equal(order.subtotal,42000);assert.equal(order.deposit,1000);assert.equal(catalogue().find(row=>row.id===p)!.reserved,25);assert.throws(()=>placeOrder(customer,payload(p)),/stock/);changeStatus(admin,order.id,'Cancelled');assert.equal(catalogue().find(row=>row.id===p)!.available,25)})
 it('excludes expired stock and prevents dispatch when reserved stock expires',()=>{const p=product();const batch=stockIn(p,10);const order=placeOrder(customer,payload(p));run('UPDATE batches SET expires_at=? WHERE id=?',new Date(Date.now()-1000).toISOString(),batch);assert.equal(catalogue().find(row=>row.id===p)!.available,0);changeStatus(admin,order.id,'Confirmed');changeStatus(admin,order.id,'Preparing');assignDriver(admin,order.id,{driver_id:driverId,eta:'10 minutes',instructions:''});assert.throws(()=>changeStatus(admin,order.id,'Out for delivery'),/expired/);assert.throws(()=>adjustStock(admin,{batch_id:batch,kind:'expired',quantity:10,reason:'Expired'}),/unreserved/);changeStatus(admin,order.id,'Cancelled');adjustStock(admin,{batch_id:batch,kind:'expired',quantity:10,reason:'Expired'});assert.equal(one('SELECT remaining FROM batches WHERE id=?',batch)!.remaining,0)})
 it('requires a driver and a valid recipient code; delivery does not mark payment paid',()=>{const p=product();stockIn(p);const order=placeOrder(customer,payload(p));changeStatus(admin,order.id,'Confirmed');changeStatus(admin,order.id,'Preparing');assert.throws(()=>changeStatus(admin,order.id,'Out for delivery'),/Assign a driver/);assignDriver(admin,order.id,{driver_id:driverId,eta:'15 minutes',instructions:'Room 4'});changeStatus(admin,order.id,'Out for delivery');assert.throws(()=>changeStatus(admin,order.id,'Delivered','000000'),/incorrect/);changeStatus(admin,order.id,'Delivered',order.customer_code);assert.equal(paymentTotals(order.id).payment_status,'Unpaid');assert.throws(()=>changeStatus(admin,order.id,'Cancelled'),/Cannot move/)})
 it('quarantines returned stock instead of silently making it saleable',()=>{const p=product();stockIn(p,5);const order=placeOrder(customer,payload(p));deliver(order.id,order.customer_code);changeStatus(admin,order.id,'Returned','','Seal broken');assert.equal(catalogue().find(row=>row.id===p)!.available,4);assert.equal(one("SELECT COUNT(*) AS n FROM stock_movements WHERE order_id=? AND kind='returned_quarantine'",order.id)!.n,1)})
 it('uses price rules on the server and requires a fresh review after price changes',()=>{const p=product();stockIn(p);const promotion=savePromotion(admin,{code:`PROMO-${id().slice(0,6)}`,title:'Test offer',offer_text:'10 percent',kind:'percentage',value:10,starts_at:new Date(Date.now()-60000).toISOString(),ends_at:future(),product_ids:[p]});const code=one('SELECT code FROM promotions WHERE id=?',promotion)!.code;const input=payload(p,2,{promotion:code});const quote=placeOrder(customer,input,true);assert.equal(quote.discount,400);assert.equal(one('SELECT reserved FROM batches WHERE product_id=?',p)!.reserved,0);run('UPDATE products SET price=2500 WHERE id=?',p);assert.throws(()=>placeOrder(customer,{...input,expected_total:quote.total}),/total changed/);const order=placeOrder(customer,input);assert.equal(order.discount,500);assert.equal(order.subtotal,5000)})
})
describe('payments, hotel commissions and privacy',()=>{
 it('freezes commission rules, earns only after paid delivery, and recovers paid commissions after refund',()=>{
  const p=product();stockIn(p);const order=placeOrder(customer,payload(p,10,{referral_code:'TEST-HOTEL'}));const commission=()=>one('SELECT * FROM commissions WHERE order_id=?',order.id)!
  assert.equal(commission().expected,2000);assert.equal(commission().earned,0)
  run('UPDATE hotels SET rule=? WHERE id=?',JSON.stringify({method:'percentage',value:40,scope:'referral',tiers:[]}),hotelId)
  recordPayment(admin,order.id,{amount:order.total,kind:'payment',method:'bank_transfer',reference:`bank-${id()}`});assert.equal(commission().earned,0)
  deliver(order.id,order.customer_code);assert.equal(commission().earned,2000)
  const paid=payout(admin,hotelId,`payout-${id()}`);assert.equal(paid.amount,2000)
  recordPayment(admin,order.id,{amount:order.total,kind:'refund',method:'bank_transfer',reference:`refund-${id()}`});assert.equal(commission().earned,0);assert.equal(commission().paid,2000);assert.throws(()=>payout(admin,hotelId,`payout-${id()}`),/No commission/)
 })
 it('does not pay referral-only commission on hotel purchases',()=>{const p=product({hotel_price:1500});stockIn(p);const order=placeOrder(manager,payload(p,2));assert.equal(order.subtotal,3000);assert.equal(one('SELECT id FROM commissions WHERE order_id=?',order.id),undefined);assert.throws(()=>placeOrder(manager,payload(p,1,{referral_code:'TEST-HOTEL'})),/cannot also/)})
 it('supports fixed and tiered per-order arrangements',()=>{assert.equal(commissionAmount(100000,{method:'fixed',value:10000,scope:'referral',tiers:[]}),10000);assert.equal(commissionAmount(200000,{method:'tiered',value:0,scope:'referral',tiers:[{threshold:0,rate:5},{threshold:150000,rate:12}]}),24000)})
 it('keeps payment references idempotent and blocks over-refunds',()=>{const p=product();stockIn(p);const order=placeOrder(customer,payload(p));const payment={amount:order.total,kind:'payment',method:'cash',reference:id()};recordPayment(admin,order.id,payment);recordPayment(admin,order.id,payment);assert.equal(paymentTotals(order.id).paid,order.total);assert.throws(()=>recordPayment(admin,order.id,{...payment,kind:'refund',amount:order.total+1,reference:id()}),/exceed/);assert.throws(()=>recordPayment(stock,order.id,payment),/permission/)})
 it('prevents other customers and hotels from seeing orders; hides purchase costs and referral personal details',()=>{const p=product();stockIn(p);const order=placeOrder(customer,payload(p,1,{referral_code:'TEST-HOTEL'}));assert.throws(()=>orderDetails(other,order.id),/not found/);assert.throws(()=>orderDetails(manager,order.id),/not found/);assert.equal('cost' in order.items[0],false);assert.equal(orderDetails(admin,order.id).customer_code,undefined);assert.equal(publicCatalogue(customer).find(row=>row.id===p)?.cost,undefined);const referred=commissionsFor(manager).find(row=>row.order_id===order.id)!;assert.equal(referred.recipient,undefined);assert.equal(referred.phone,undefined);assert.equal(listOrders(other).some(o=>o.id===order.id),false)})
})
describe('secure links, outbox, exports and recovery',()=>{
 it('uses single-use invitation tokens and revokes sessions on password reset',()=>{const account=user('customer');const token=tokenFor(account.id,'invite');redeemToken(token,'invite','A-new-password-2026');assert.throws(()=>redeemToken(token,'invite','Again-password-2026'),/invalid/);assert(passwordMatches('A-new-password-2026',one('SELECT password FROM users WHERE id=?',account.id)!.password));assert(!passwordMatches('wrong',one('SELECT password FROM users WHERE id=?',account.id)!.password))})
 it('limits driver links to assigned order data and confirms without an account',()=>{const p=product();stockIn(p);const order=placeOrder(customer,payload(p));changeStatus(admin,order.id,'Confirmed');changeStatus(admin,order.id,'Preparing');assignDriver(admin,order.id,{driver_id:driverId,eta:'20 minutes',instructions:'Reception'});const message=one("SELECT message FROM notifications WHERE order_id=? AND audience='driver'",order.id)!.message;const token=message.match(/\/delivery\/([0-9a-f]{64})/)[1];assert.equal((deliveryDetails(token) as any).customer_code,undefined);assert.throws(()=>confirmDelivery(token,order.customer_code),/not been dispatched/);changeStatus(admin,order.id,'Out for delivery');confirmDelivery(token,order.customer_code);assert.equal(orderDetails(customer,order.id).status,'Delivered');run('UPDATE orders SET driver_token_expires=? WHERE id=?',new Date(Date.now()-1000).toISOString(),order.id);assert.throws(()=>deliveryDetails(token),/expired/)})
 it('leaves messages queued when external providers are not configured',async()=>{const queued=one("SELECT COUNT(*) AS n FROM notifications WHERE channel='sms' AND status='queued'")!.n;assert(queued>0);assert.equal((await processNotifications()).length,0);assert.equal(one("SELECT COUNT(*) AS n FROM notifications WHERE channel='sms' AND status='queued'")!.n,queued)})
 it('creates scoped PDF and CSV reports and prevents spreadsheet formulas',async()=>{const orders=listOrders(customer);const report=reportRows(customer,'receipt','1970','2999',orders[0].id);const pdf=await pdfReport(report,'Test period');assert.equal(Buffer.from(pdf).subarray(0,4).toString(),'%PDF');assert.throws(()=>reportRows(other,'receipt','1970','2999',orders[0].id),/not found/);const csv=csvReport({title:'Test',headers:['Name'],rows:[['=HYPERLINK("evil")']]});assert(csv.includes("'=HYPERLINK"));assert.throws(()=>reportRows(customer,'stock','1970','2999'),/permission/)})
 it('backs up a consistent database including committed transactions',async()=>{const destination=path.join(path.dirname(process.env.DATABASE_PATH!),'backup.sqlite');await db().backup(destination);const Database=(await import('better-sqlite3')).default;const copy=new Database(destination,{readonly:true});assert.equal(copy.pragma('integrity_check',{simple:true}),'ok');assert.equal((copy.prepare('SELECT COUNT(*) AS n FROM orders').get() as any).n,one('SELECT COUNT(*) AS n FROM orders')!.n);copy.close()})
})
