-- Versioned PostgreSQL application schema. Existing public tables are preserved by the migration runner.
CREATE TYPE user_role AS ENUM ('admin', 'sales', 'stock', 'delivery', 'customer', 'hotel_manager', 'hotel_staff');
CREATE TYPE order_status AS ENUM ('Pending', 'Confirmed', 'Preparing', 'Out for delivery', 'Delivered', 'Cancelled', 'Failed delivery', 'Returned');
CREATE TYPE payment_kind AS ENUM ('payment', 'refund');
CREATE TYPE payment_method AS ENUM ('cash', 'bank_transfer', 'card', 'deposit_return');
CREATE TYPE allocation_state AS ENUM ('reserved', 'released', 'sold', 'returned');
CREATE TYPE notification_channel AS ENUM ('sms', 'email', 'dashboard');
CREATE TYPE notification_status AS ENUM ('queued', 'sending', 'submitted', 'sent', 'delivered', 'failed', 'unknown');
CREATE TYPE support_status AS ENUM ('Open', 'Resolved');

    CREATE TABLE hotels (id TEXT PRIMARY KEY, name TEXT NOT NULL, contact TEXT NOT NULL, phone TEXT NOT NULL, address TEXT NOT NULL, instructions TEXT NOT NULL DEFAULT '', code TEXT UNIQUE NOT NULL, active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)), rule TEXT NOT NULL DEFAULT '{"method":"percentage","value":0,"scope":"referral","tiers":[]}', created_at TEXT NOT NULL);
    CREATE TABLE users (id TEXT PRIMARY KEY, email TEXT UNIQUE NOT NULL, name TEXT NOT NULL, phone TEXT NOT NULL DEFAULT '', phone_verified INTEGER NOT NULL DEFAULT 0 CHECK (phone_verified IN (0,1)), password TEXT, role user_role NOT NULL DEFAULT 'customer', hotel_id TEXT REFERENCES hotels(id), active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)), notifications INTEGER NOT NULL DEFAULT 1 CHECK (notifications IN (0,1)), created_at TEXT NOT NULL);
    CREATE TABLE sessions (token TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), expires_at TEXT NOT NULL);
    CREATE TABLE tokens (token TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), purpose TEXT NOT NULL, expires_at TEXT NOT NULL, used_at TEXT);
    CREATE TABLE rate_limits (key TEXT PRIMARY KEY, count INTEGER NOT NULL, expires_at BIGINT NOT NULL);
    CREATE TABLE products (id TEXT PRIMARY KEY, name TEXT NOT NULL, brand TEXT NOT NULL DEFAULT '', category TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', image TEXT NOT NULL DEFAULT '/images/mango-coast.png', volume TEXT NOT NULL DEFAULT '', unit TEXT NOT NULL DEFAULT 'bottle', unit_size INTEGER NOT NULL DEFAULT 1 CHECK(unit_size>0), price INTEGER NOT NULL CHECK(price>=0), hotel_price INTEGER, cost INTEGER NOT NULL DEFAULT 0 CHECK(cost>=0), sku TEXT UNIQUE NOT NULL, reorder_level INTEGER NOT NULL DEFAULT 10, min_qty INTEGER NOT NULL DEFAULT 1, deposit INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)), created_at TEXT NOT NULL, units TEXT NOT NULL DEFAULT '[]');
    CREATE TABLE batches (id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id), label TEXT NOT NULL, expires_at TEXT NOT NULL, remaining INTEGER NOT NULL CHECK(remaining>=0), reserved INTEGER NOT NULL DEFAULT 0 CHECK(reserved>=0 AND reserved<=remaining), cost INTEGER NOT NULL CHECK(cost>=0), created_at TEXT NOT NULL);
    CREATE TABLE orders (id TEXT PRIMARY KEY, number TEXT UNIQUE NOT NULL, user_id TEXT NOT NULL REFERENCES users(id), hotel_id TEXT REFERENCES hotels(id), referral_id TEXT REFERENCES hotels(id), recipient TEXT NOT NULL, phone TEXT NOT NULL, address TEXT NOT NULL, instructions TEXT NOT NULL DEFAULT '', delivery_window TEXT NOT NULL DEFAULT '', status order_status NOT NULL DEFAULT 'Pending', subtotal INTEGER NOT NULL, discount INTEGER NOT NULL DEFAULT 0, delivery_fee INTEGER NOT NULL DEFAULT 0, tax INTEGER NOT NULL DEFAULT 0, deposit INTEGER NOT NULL DEFAULT 0, total INTEGER NOT NULL, payment_method payment_method NOT NULL, promotion TEXT, driver TEXT, code_hash TEXT NOT NULL, customer_code TEXT NOT NULL, driver_token TEXT, driver_token_expires TEXT, idempotency_key TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(user_id,idempotency_key));
    CREATE TABLE order_items (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), product_id TEXT NOT NULL REFERENCES products(id), name TEXT NOT NULL, quantity INTEGER NOT NULL CHECK(quantity>0), base_quantity INTEGER NOT NULL, unit TEXT NOT NULL, unit_price INTEGER NOT NULL, cost INTEGER NOT NULL DEFAULT 0, deposit INTEGER NOT NULL DEFAULT 0);
    CREATE TABLE allocations (id TEXT PRIMARY KEY, item_id TEXT NOT NULL REFERENCES order_items(id), batch_id TEXT NOT NULL REFERENCES batches(id), quantity INTEGER NOT NULL, state allocation_state NOT NULL DEFAULT 'reserved');
    CREATE TABLE stock_movements (id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id), batch_id TEXT REFERENCES batches(id), order_id TEXT REFERENCES orders(id), kind TEXT NOT NULL, quantity INTEGER NOT NULL, cost INTEGER NOT NULL DEFAULT 0, reason TEXT NOT NULL, actor_id TEXT REFERENCES users(id), created_at TEXT NOT NULL);
    CREATE TABLE order_history (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), status order_status NOT NULL, note TEXT NOT NULL DEFAULT '', actor_id TEXT REFERENCES users(id), created_at TEXT NOT NULL);
    CREATE TABLE payments (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), amount INTEGER NOT NULL CHECK(amount>0), kind payment_kind NOT NULL, method payment_method NOT NULL, reference TEXT UNIQUE NOT NULL, actor_id TEXT REFERENCES users(id), created_at TEXT NOT NULL);
    CREATE TABLE commissions (id TEXT PRIMARY KEY, order_id TEXT UNIQUE NOT NULL REFERENCES orders(id), hotel_id TEXT NOT NULL REFERENCES hotels(id), rule TEXT NOT NULL, eligible INTEGER NOT NULL, expected INTEGER NOT NULL, earned INTEGER NOT NULL DEFAULT 0, paid INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
    CREATE TABLE payouts (id TEXT PRIMARY KEY, hotel_id TEXT NOT NULL REFERENCES hotels(id), amount INTEGER NOT NULL, reference TEXT UNIQUE NOT NULL, actor_id TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL);
    CREATE TABLE payout_items (payout_id TEXT NOT NULL REFERENCES payouts(id), commission_id TEXT NOT NULL REFERENCES commissions(id), amount INTEGER NOT NULL, PRIMARY KEY(payout_id,commission_id));
    CREATE TABLE drivers (id TEXT PRIMARY KEY, name TEXT NOT NULL, phone TEXT NOT NULL, vehicle TEXT NOT NULL, registration TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)));
    CREATE TABLE promotions (id TEXT PRIMARY KEY, code TEXT UNIQUE NOT NULL, title TEXT NOT NULL, offer_text TEXT NOT NULL, image TEXT NOT NULL DEFAULT '', color TEXT NOT NULL DEFAULT '#ff5405', template TEXT NOT NULL DEFAULT 'banner', button TEXT NOT NULL DEFAULT 'Shop now', product_ids TEXT NOT NULL DEFAULT '[]', audience TEXT NOT NULL DEFAULT 'all', kind TEXT NOT NULL DEFAULT 'percentage', value INTEGER NOT NULL, starts_at TEXT NOT NULL, ends_at TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)));
    CREATE TABLE notifications (id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id), audience TEXT NOT NULL, order_id TEXT REFERENCES orders(id), channel notification_channel NOT NULL, recipient TEXT NOT NULL, message TEXT NOT NULL, dedup_key TEXT UNIQUE NOT NULL, status notification_status NOT NULL DEFAULT 'queued', attempts INTEGER NOT NULL DEFAULT 0, provider_id TEXT, error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE audit (id TEXT PRIMARY KEY, actor_id TEXT REFERENCES users(id), action TEXT NOT NULL, entity TEXT NOT NULL, entity_id TEXT NOT NULL, detail TEXT NOT NULL, created_at TEXT NOT NULL);
    CREATE TABLE addresses (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), label TEXT NOT NULL, address TEXT NOT NULL, is_default INTEGER NOT NULL DEFAULT 0 CHECK (is_default IN (0,1)));
    CREATE TABLE favourites (user_id TEXT NOT NULL REFERENCES users(id), product_id TEXT NOT NULL REFERENCES products(id), PRIMARY KEY(user_id,product_id));
    CREATE TABLE support (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), order_id TEXT REFERENCES orders(id), message TEXT NOT NULL, reply TEXT NOT NULL DEFAULT '', status support_status NOT NULL DEFAULT 'Open', created_at TEXT NOT NULL);
    CREATE TABLE expenses (id TEXT PRIMARY KEY, amount INTEGER NOT NULL CHECK(amount>0), description TEXT NOT NULL, date TEXT NOT NULL, actor_id TEXT NOT NULL REFERENCES users(id));
    CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
    CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id,created_at);
    CREATE INDEX IF NOT EXISTS idx_orders_hotel ON orders(hotel_id,created_at);
    CREATE INDEX IF NOT EXISTS idx_batches_product ON batches(product_id,expires_at);
    CREATE INDEX IF NOT EXISTS idx_notification_status ON notifications(status,created_at);
  
CREATE UNIQUE INDEX users_email_case_insensitive ON users (lower(email));
CREATE INDEX sessions_user_idx ON sessions(user_id);
CREATE INDEX sessions_expiry_idx ON sessions(expires_at);
CREATE INDEX tokens_user_purpose_idx ON tokens(user_id,purpose);
CREATE INDEX payments_order_idx ON payments(order_id);
CREATE INDEX allocations_item_idx ON allocations(item_id);
CREATE INDEX commissions_hotel_idx ON commissions(hotel_id);
ALTER TABLE users ADD CONSTRAINT hotel_role_membership CHECK ((role IN ('hotel_manager','hotel_staff')) = (hotel_id IS NOT NULL));
ALTER TABLE products ADD CONSTRAINT product_values CHECK (min_qty>0 AND reorder_level>=0 AND deposit>=0 AND (hotel_price IS NULL OR hotel_price>=0));
ALTER TABLE orders ADD CONSTRAINT order_values CHECK (subtotal>=0 AND discount>=0 AND discount<=subtotal AND delivery_fee>=0 AND tax>=0 AND deposit>=0 AND total=subtotal-discount+delivery_fee+tax+deposit);
ALTER TABLE payments ADD CONSTRAINT positive_payment CHECK (amount>0);
ALTER TABLE allocations ADD CONSTRAINT positive_allocation CHECK (quantity>0);
ALTER TABLE notifications ADD CONSTRAINT nonnegative_attempts CHECK (attempts>=0);
ALTER TABLE promotions ADD CONSTRAINT promotion_values CHECK (value>=0 AND (kind<>'percentage' OR value<=100) AND ends_at>starts_at AND kind IN ('percentage','fixed') AND audience IN ('all','customer','hotel'));
