'use client'
import { useEffect,useState } from 'react'
import s from './platform.module.css'
import { mutate } from '@/lib/client-api'
type Row=Record<string,any>
async function request(query='',body?:Row) {
 const response=await fetch(`/api/sms${query}`,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'})
 const result=await response.json();if(!response.ok)throw new Error(result.error);return result.data
}
export default function SmsDashboard() {
 const [recipients,setRecipients]=useState<Row[]>([])
 const [data,setData]=useState<Row>({logs:[],metrics:{},campaigns:[]}),[settings,setSettings]=useState<Row>({}),[templates,setTemplates]=useState<Row>({}),[type,setType]=useState('OTP'),[template,setTemplate]=useState(''),[filters,setFilters]=useState<Row>({}),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[group,setGroup]=useState('VERIFIED_CUSTOMERS'),[selected,setSelected]=useState(''),[text,setText]=useState(''),[preview,setPreview]=useState<Row|null>(null)
 async function load(){const [dashboard,config]=await Promise.all([request('?'+new URLSearchParams(Object.entries(filters).filter(([,v])=>v) as [string,string][])),request('?resource=settings')]);setData(dashboard);setSettings(config.values);setTemplates(config.templates);setRecipients(config.recipients)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[])
 useEffect(()=>{setTemplate(templates[type]||'')},[type,templates])
 async function action(fn:()=>Promise<unknown>,notice:string){setBusy(true);setError('');setMessage('');try{await fn();setMessage(notice);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function campaignPayload(){return {group,selected:selected.split(/[\s,]+/).filter(Boolean),message:text,campaignId:preview?.campaignId||crypto.randomUUID()}}
 return <div>
  {error&&<p className={s.error} role="alert">{error}</p>}{message&&<p className={s.notice} role="status">{message}</p>}
  <article className={s.panel}><h2>SMS overview</h2><div className={s.toolbar}>{Object.entries(data.metrics||{}).map(([key,value])=><span key={key}><strong>{String(value)}</strong> {key} &nbsp;</span>)}</div><p className={s.hint}>Successful counts provider acceptance, sent and delivered messages. Unknown outcomes require reconciliation before retrying. Today uses UTC.</p></article>
  <article className={s.panel}><h2>SMS settings</h2><form className={s.form} onSubmit={e=>{e.preventDefault();action(()=>request('',{action:'settings',...Object.fromEntries(Object.entries(settings).filter(([k])=>!k.startsWith('sms_template_')).map(([k,v])=>[k,k.endsWith('_enabled')?v==='true':v]))}),'SMS settings saved.')}}>
   <label>Provider<select value={settings.sms_provider||'macksms'} onChange={e=>setSettings({...settings,sms_provider:e.target.value})}><option value="macksms">MackSMS</option><option value="twilio">Twilio</option></select></label>
   {['sms_sender_id','sms_admin_phone','sms_shop_location'].map(key=><label key={key}>{({sms_sender_id:'Registered sender ID',sms_admin_phone:'Administrator phone (or use admin accounts)',sms_shop_location:'Actual shop pickup location'} as Row)[key]}<input required={key!=='sms_admin_phone'} value={settings[key]||''} onChange={e=>setSettings({...settings,[key]:e.target.value})}/></label>)}
   {['sms_enabled','sms_otp_enabled','sms_order_enabled','sms_driver_enabled','sms_customer_enabled','sms_admin_enabled'].map(key=><label className={s.checkbox} key={key}><input type="checkbox" checked={settings[key]==='true'} onChange={e=>setSettings({...settings,[key]:String(e.target.checked)})}/>{key.replace('sms_','').replaceAll('_',' ')}</label>)}
   <p className={s.hint}>Disabling OTP pauses new registrations. Provider credentials remain in server environment variables.</p><button disabled={busy} className={s.primary}>Save settings</button>
  </form></article>
  <article className={s.panel}><h2>Message templates</h2><form className={s.form} onSubmit={e=>{e.preventDefault();action(()=>request('',{action:'template',type,message:template}),'Template saved.')}}><label>Notification type<select value={type} onChange={e=>setType(e.target.value)}>{Object.keys(templates).map(key=><option key={key}>{key}</option>)}</select></label><label>Message<textarea rows={5} maxLength={1600} value={template} onChange={e=>setTemplate(e.target.value)}/></label><p className={s.hint}>{'Variables: {{customerName}}, {{orderNumber}}, {{orderTotal}}, {{orderStatus}}, {{driverName}}, {{driverPhone}}, {{customerPhone}}, {{customerLocation}}, {{shopName}}, {{shopLocation}}, {{orderItems}}, {{adminPortal}}, {{deliveryInstructions}}, {{deliveryLink}}, {{title}}, {{code}} (OTP only).'}</p><button disabled={busy} className={s.primary}>Save template</button></form></article>
  <article className={s.panel}><h2>Bulk SMS</h2><div className={s.form}><label>Recipients<select value={group} onChange={e=>{setGroup(e.target.value);setPreview(null)}}>{['ALL_CUSTOMERS','VERIFIED_CUSTOMERS','ACTIVE_CUSTOMERS','DRIVERS','ADMINS','SELECTED_USERS'].map(value=><option key={value}>{value}</option>)}</select></label>{group==='SELECTED_USERS'&&<label>Select users<select multiple size={6} value={selected.split(',').filter(Boolean)} onChange={e=>{setSelected(Array.from(e.target.selectedOptions).map(option=>option.value).join(','));setPreview(null)}}>{recipients.map(user=><option key={user.id} value={user.id}>{user.name} ? {user.phone}</option>)}</select></label>}<label>Message<textarea maxLength={1000} rows={4} value={text} onChange={e=>{setText(e.target.value);setPreview(null)}}/></label><p className={s.hint}>Customer campaigns respect SMS preferences. Active customers have ordered in the last 90 days. Sending runs in the background worker.</p><button disabled={busy||!text.trim()} className={s.secondary} onClick={()=>action(async()=>setPreview(await request('',{action:'preview',...campaignPayload()})),'Preview ready.')}>Preview recipients and message</button>{preview&&<><p>{preview.count} recipients · {text.length} characters</p><blockquote>{preview.preview}</blockquote><button disabled={busy||!preview.count} className={s.primary} onClick={()=>action(async()=>{await request('',{action:'campaign',...campaignPayload()});setPreview(null);setText('')},'Campaign queued for the worker.')}>Queue campaign</button></>}</div><h3>Campaign history</h3>{data.campaigns.map((item:Row)=><p key={item.id}>{item.recipient_group}: {item.cursor}/{item.total} queued · {item.completed_at?'Queueing complete':'Waiting for worker'} · {new Date(item.created_at).toLocaleString()}</p>)}</article>
  <article className={s.panel}><h2>SMS history</h2><div className={s.toolbar}>{['from','to','status','type','recipient','order'].map(key=><label key={key}>{key}<input type={['from','to'].includes(key)?'date':'text'} value={filters[key]||''} onChange={e=>setFilters({...filters,[key]:e.target.value})}/></label>)}<button disabled={busy} onClick={()=>action(async()=>{},'History refreshed.')} className={s.secondary}>Apply filters</button><button disabled={busy} onClick={()=>action(()=>mutate('notifications.process',{}),'Queue processed.')} className={s.secondary}>Process queue</button><button disabled={busy} onClick={()=>action(()=>mutate('notifications.refresh',{}),'Statuses refreshed.')} className={s.secondary}>Refresh delivery reports</button></div><p className={s.hint}>Latest 500 matching messages. End date is exclusive. Status filters: queued, submitted, sent, delivered, failed, unknown.</p><div style={{overflowX:'auto'}}><table style={{width:'100%',textAlign:'left'}}><thead><tr>{['Recipient','Type / order','Message','Status','Date','Action'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{data.logs.map((row:Row)=><tr key={row.id}><td>{row.recipient}<br/>{row.audience}</td><td>{row.notification_type}<br/>{row.order_number}</td><td style={{minWidth:220}}>{row.message}</td><td>{row.status}<br/>{row.error}</td><td>{new Date(row.created_at).toLocaleString()}</td><td>{row.status==='failed'&&row.notification_type!=='OTP'&&<button disabled={busy} onClick={()=>action(()=>mutate('notifications.retry',{id:row.id}),'Retry queued.')}>Retry</button>}</td></tr>)}</tbody></table></div></article>
 </div>
}
